version: '3.7'

services:
  sentry-redis:
    image: redis:latest
    container_name: sentry-redis
    hostname: sentry-redis
    restart: always
    networks:
      sentry_net:
        ipv4_address: 172.29.0.2
    volumes:
      - './data/sentry/redis/data:/data'
  
  sentry-postgres:
    image: postgres:latest
    container_name: sentry-postgres
    hostname: sentry-postgres
    restart: always
    environment:
      POSTGRES_USER: sentry
      POSTGRES_PASSWORD: Aa123456
      POSTGRES_DB: sentry
    networks:
      sentry_net:
        ipv4_address: 172.29.0.3
    volumes:
      - './data/sentry/postgres:/var/lib/postgresql/data'

  sentry-base:
    image: sentry:latest
    container_name: sentry-base
    hostname: sentry-base
    restart: always
    ports:
      - '9000:9000'
    env_file:
      - .env
    depends_on:
      - sentry-redis
      - sentry-postgres
    networks:
      sentry_net:
        ipv4_address: 172.29.0.4
    volumes:
      - './data/sentry/sentry:/var/lib/sentry/files'

  sentry-worker:
    image: sentry:latest
    container_name: sentry-worker
    hostname: sentry-worker
    restart: always
    env_file:
      - .env
    depends_on:
      - sentry-redis
      - sentry-postgres
    command: "sentry run worker"
    networks:
      sentry_net:
        ipv4_address: 172.29.0.5
    volumes:
      - './data/sentry/sentry:/var/lib/sentry/files'

  nginx:
    restart: unless-stopped
    image: nginx:latest
    container_name: sentry-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 9800:9800
    networks:
      sentry_net:
        ipv4_address: 172.29.0.6

networks:
  sentry_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/16
